### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by adamrt** [mmatyas/fft#1]
Hey @mmatyas !

I've been hunting around for the source for this amazing map viewer. I see there is a minified version on the `gh-pages` branch, and I can obviously pretty print it, but I was curious if you were going to release the actual project code/structure?

Thanks!

**Comment by mmatyas** [comment]
Hi, glad to hear you liked it! I didn't really plan to release the source, as it's pretty much complete in its current form, for what I planned it to do. There could be always some improvements though, so I'm not strongly against it; maybe some day!

**Comment by adamrt** [comment]
Very cool. I'm mostly interested in it for my own study. It seems like your lighting is much better than some of the older FFT map viewers I've seen. 

I was just getting started on creating a basic map viewer in C to improve my limited knowledge of the language when I ran across this. 

If you're open to sharing it directly with me or publicly I would be super thankful. If not that's cool too. 

Either way, thank you for creating it.

**Comment by mmatyas** [comment]
> Very cool. I'm mostly interested in it for my own study. It seems like your lighting is much better than some of the older FFT map viewers I've seen.

I'm surprised to hear that! I'm somewhat bad with shaders actually, pretty sure I wrote it with the help of some GL tutorials. Here's the relevant part in the vertex shader:

```glsl
    vec3 light_sum = vec3(0.0);
    for (int i = 0; i < NUM_POINT_LIGHTS; i++) {
        vec3 direction = normalize(pointLights[i].position - position.xyz);
        float intensity = clamp(dot(normal, direction), 0.0, 1.0);
        light_sum += pointLights[i].color * intensity;
    }
    v_light = (ambientLightColor + light_sum) * 2.0;
```

where `pointLights[NUM_POINT_LIGHTS]` and `ambientLightColor` come from the map data, `normal` and `position` are the the properties of the vertex, and `v_light` is the varying passed to the fragment shader, where it just multiplies the final fragment color.

**Comment by adamrt** [comment]
Hey @mmatyas, have you given any thought to release this code? I've been working on my own map viewer as a learning experience since I opened this ticket. As a way to learn a new language and a bit of OpenGL. I have it running but I was hoping to look at the code you use for parsing(bin,iso)/applying textures. My map models are correct and I have the textures being applied but they are very wonky. Been stuck for a few days.

Thanks again
Adam

**Comment by mmatyas** [comment]
Yeah reading game files from a raw disk image in the browser might not be the most common thing on a webpage. The actual sector offsets are hardcoded for me too because I didn't want to deal with the disk's file system.

Perhaps it would help you to have a smaller scope? Ie. making sure that the map viewing works on its own with already exported files.

With the textures, for example, if the base grayscale texture works, that's a good start. That one should work out of the box, or with some axis flipping, depending on the coordinate system you use. Once that looks good, you could color the texture with the map palette – I did this by saving it to a texture and sampling it in the shaders, but a manual data setup should work fine too.
